spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  read-data-source-poll-pattern: 1
  write:
    url: jdbc:mysql://rm-bp1y4sxrvbln69yi9o.mysql.rds.aliyuncs.com/crm_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: hscrm
    password: hscrm@123
  read:
    - url: jdbc:mysql://rm-bp1y4sxrvbln69yi9o.mysql.rds.aliyuncs.com/crm_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: hscrm
      password: hscrm@123
    - url: jdbc:mysql://rm-bp1y4sxrvbln69yi9o.mysql.rds.aliyuncs.com/crm_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: hscrm
      password: hscrm@123
mybatis:
  config-location: classpath:mybatis-config.xml