spring:
  application:
    name: management
ds-helper:
  read-data-source-poll-pattern: 1
  write:
    url: jdbc:mysql://rm-bp1y4sxrvbln69yi9o.mysql.rds.aliyuncs.com/crm_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: hscrm
    password: hscrm@123
    initial-size: 10
    max-active: 50
    filters: stat,wall
    connectionProperties: druid.stat.logSlowSql=true;druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1
  read:
    - url: jdbc:mysql://rm-bp1y4sxrvbln69yi9o.mysql.rds.aliyuncs.com/crm_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: hscrm
      password: hscrm@123
      initial-size: 10
      max-active: 50
      filters: stat,wall
      connectionProperties: druid.stat.logSlowSql=true;druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1
    - url: jdbc:mysql://rm-bp1y4sxrvbln69yi9o.mysql.rds.aliyuncs.com/crm_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: hscrm
      password: hscrm@123
      initial-size: 10
      max-active: 50
      filters: stat,wall
      connectionProperties: druid.stat.logSlowSql=true;druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1
pagehelper:
  helper-dialect: mysql
logging:
  file: ${spring.application.name}