spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: management
datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  read-data-source-poll-pattern: 1
  write:
    url: jdbc:mysql://192.168.227.129:3306/driftBottle?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  read:
    - url: jdbc:mysql://192.168.227.130:3306/driftBottle?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
    - url: jdbc:mysql://192.168.227.130:3306/driftBottle?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
mybatis:
  config-location: classpath:mybatis-config.xml
logging:
  file: ${spring.application.name}