package com.yongle.nuwa.model.demo;

import java.io.Serializable;

public class Demo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.rank_int
     *
     * @mbg.generated
     */
    private Integer rankInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.rank_tinyint
     *
     * @mbg.generated
     */
    private Byte rankTinyint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.rank_smallint
     *
     * @mbg.generated
     */
    private Short rankSmallint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table demo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.id
     *
     * @return the value of demo.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.id
     *
     * @param id the value for demo.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.name
     *
     * @return the value of demo.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.name
     *
     * @param name the value for demo.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.rank_int
     *
     * @return the value of demo.rank_int
     *
     * @mbg.generated
     */
    public Integer getRankInt() {
        return rankInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.rank_int
     *
     * @param rankInt the value for demo.rank_int
     *
     * @mbg.generated
     */
    public void setRankInt(Integer rankInt) {
        this.rankInt = rankInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.rank_tinyint
     *
     * @return the value of demo.rank_tinyint
     *
     * @mbg.generated
     */
    public Byte getRankTinyint() {
        return rankTinyint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.rank_tinyint
     *
     * @param rankTinyint the value for demo.rank_tinyint
     *
     * @mbg.generated
     */
    public void setRankTinyint(Byte rankTinyint) {
        this.rankTinyint = rankTinyint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.rank_smallint
     *
     * @return the value of demo.rank_smallint
     *
     * @mbg.generated
     */
    public Short getRankSmallint() {
        return rankSmallint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.rank_smallint
     *
     * @param rankSmallint the value for demo.rank_smallint
     *
     * @mbg.generated
     */
    public void setRankSmallint(Short rankSmallint) {
        this.rankSmallint = rankSmallint;
    }
}